apiVersion: v1
kind: Service
metadata:
  name: fat-service
  labels:
    app: fat-service
    tier: backend
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: fat-service
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fat-service
spec:
  selector:
    matchLabels:
      app: fat-service
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: fat-service
        tier: backend
        deployment: v1
    spec:
      containers:
        - name: fat-service
          image: 992382794894.dkr.ecr.us-east-1.amazonaws.com/fat-service
          resources:
            requests:
              cpu: 300m
              memory: 528Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
              # If your cluster config does not include a dns service, then to
              # instead access environment variables to find service host
              # info, comment out the 'value: dns' line above, and uncomment the
              # line below:
              # value: env
          ports:
            - containerPort: 8080
          imagePullPolicy: "Always"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fat-service
                port:
                  number: 80
